Aws cloudwatch
samsara/trackit pull request #3
Opened 2018-10-27 16:09 UTC by DayoOliyide

Trackit can now push metrics to cloudwatch

2018-10-27 16:21 UTC, BrunoBonacci commented on README.md
> +    :namespace                   "trackit-namespace"
```suggestion
    :namespace                   "trackit"
```
For uniformity, all other reporters use a `prefix` called `trackit`.
could you please use the same here?

2018-10-27 16:27 UTC, BrunoBonacci requested changes

2018-10-27 16:27 UTC, BrunoBonacci commented on README.md
> +    :async-client                (.build (AmazonCloudWatchAsyncClientBuilder/standard))
Does make sense to expose this option? is any other alternative?

2018-10-27 16:27 UTC, BrunoBonacci commented on trackit-cloudwatch/src/samsara/trackit/reporter_cloudwatch.clj
> +    :or   {async-client                (.build (AmazonCloudWatchAsyncClientBuilder/standard))
again, not too sure it useful to have this as a configurable option

2018-10-27 20:13 UTC, DayoOliyide commented on README.md
> +    :namespace                   "trackit-namespace"
I'll change the :namespace value. However, to my knowledge prefix doesn't really exist in 
cloudwatch metrics world. It's mainly namespace, metric and dimensions. I don't see how prefix will translate.

2018-10-27 20:24 UTC, DayoOliyide commented on trackit-cloudwatch/src/samsara/trackit/reporter_cloudwatch.clj
> +    :or   {async-client                (.build (AmazonCloudWatchAsyncClientBuilder/standard))
I've removed the async-client from the documentation and the start-reporting! multimethod.
I would still want to keep it as an option in the cloudwatch reporter, as I've come across 
an issue where the apparent solution was to begin a subsegment for cloudwatch before each
call to cloudwatch.
There may be a better solution, but I'd like to keep this option open until I find it.

2018-10-29 11:30 UTC, merged

2018-10-29 22:34 UTC, BrunoBonacci commented
released with`[samsara/trackit-all "0.8.0"]`